name: Build Multiwfn Linux64

on:
  push:
    branches:
      - master
      
env:
  Multiwfn_version:  Multiwfn_3.8_dev_src_Linux
  
jobs:
  Linux-64:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install Dislin libraries
      run: |
        wget https://www.dislin.de/downloads/linux/i586_64/dislin-11.5.linux.i586_64.tar.gz
        tar -xf dislin-11.5.linux.i586_64.tar.gz
        export DISLIN=$PWD/dislin
        cd dislin-11.5
        ./INSTALL
        cd ..
        ls $DISLIN/                  
        echo "PATH=$PATH:$DISLIN/bin" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$DISLIN:$LD_LIBRARY_PATH" >> $GITHUB_ENV 
        sudo apt install p7zip-full libxm4 libmotif-dev libgl1-mesa-dev 

    - name: Install fortran
      uses: fortran-lang/setup-fortran@v1
      id: setup-fortran
      with:
        compiler: intel-classic
        version: 2021.10

    - name: Test ifort
      run: |
        echo ${{ env.FC }} 
        echo ${{ steps.setup-fortran.outputs.fc }} 
        ifort --version

    - name: Download Multiwfn
      run: |
        rm -rf ${{env.Multiwfn_version}}
        curl -L http://sobereva.com/multiwfn/misc/${{env.Multiwfn_version}}.zip -o Multiwfn_src.zip
        7z x Multiwfn_src.zip

    - name: Build static flint
      run: |
        vcpkg install flint:x64-linux-release
        ls /usr/local/share/vcpkg/packages/flint_x64-linux-release/lib

    - name: Compile Multiwfn
      run: |
        cd ${{env.Multiwfn_version}}
        sed -i 's|INCLUDE = -I./ -I./ext|& -I /usr/local/share/vcpkg/packages/flint_x64-linux-release/include|' Makefile 
        sed -i 's|^LIB_base =.*|&  /usr/local/share/vcpkg/packages/flint_x64-linux-release/lib/libflint.a|' Makefile
        cat Makefile
        make WITH_FD=1 OS=Ubuntu -j4 
