name: Build Multiwfn on Windows

on:
  push:
    branches:
      - master

env:
  Multiwfn_version:  Multiwfn_3.8_dev_src_Linux
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/c95a3b26-fc45-496c-833b-df08b10297b9/w_HPCKit_p_2024.1.0.561_offline.exe
  WINDOWS_FORTRAN_COMPONENTS: intel.oneapi.win.ifort-compiler

jobs:
  Windows:
    runs-on: windows-2022

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Fortran compiler
        run: |
          .github/scripts/install_windows.bat ${{env.WINDOWS_HPCKIT_URL}} ${{env.WINDOWS_FORTRAN_COMPONENTS}}

      - name: Download Multiwfn source code
        run: |
          curl -L http://sobereva.com/multiwfn/misc/${{env.Multiwfn_version}}.zip -o Multiwfn_src.zip
          7z x Multiwfn_src.zip
        
      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.29

      - name: Compile Multiwfn
        shell: cmd
        run: |
          cd ${{env.Multiwfn_version}}
          copy ..\CMakeLists.txt . /Y
          copy ..\disifl_d.lib . /Y
          md build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -A x64
          cmake --build . --config Release --target Multiwfn
          
          dir 
