name: Test Multiwfn MacOS-14-arm64
on:
  push:
    branches: [master]

jobs:
  MacOS-Arm64:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check system
      run: |
        echo "macOS version: $(sw_vers -productVersion)"
        echo "macOS kernel: $(uname -r)"
        echo "macOS arch: $(uname -m)"

    - name: Fix Multiwfn path
      run: |
        unzip -o Multiwfn3.8_latest_MacOS.zip
        chmod a+x Multiwfn
        install_name_tool -change /Users/runner/work/Multiwfn_compile/Multiwfn_compile/dislin/libdislin_d.dylib @loader_path/libdislin_d.dylib Multiwfn
        
    - name: Install dependencies
      run: | 
        brew install --cask xquartz
        brew install ffmpeg pv 
       
    - name: Start XQuartz (X11 server)
      run: |
        sudo /opt/X11/libexec/privileged_startx || true
        export DISPLAY=:99
        ffmpeg -f avfoundation -list_devices true -i ""

    - name: Test
      run: |
          ffmpeg -f avfoundation -framerate 30 -video_size 1920x1080 -i "0"  -c:v libx264 -crf 18 output.mp4 &
          # ffmpeg -video_size 1280x1024 -framerate 25 -f x11grab -i :99.0 -t 15 out.mp4 &
          
          # 运行程序并自动结束
          {
            ./Multiwfn misc/examples/phenylalanineresiduestrimer.xyz <<< "0" &
            sleep 5
            pkill -f "Multiwfn"  # 强制结束程序
          }

          # 确保录制完成
          sleep 5

    - name: Upload recording
      uses: actions/upload-artifact@v4
      with:
        name: gui-recording
        path: out.mp4
        
