name: Build latest Mutiwfn using mingw64 on Windows

on:
  push:
    branches:
      - master

env:
  Multiwfn_version:  Multiwfn_3.8_dev_src_Linux

jobs:
 Mingw64Build:
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: "MinGW Makefiles"

    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: Set up Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          7zip:p
          blas:p
          openblas:p
          mpfr:p
          gmp:p
          flint:p

    - name: Download Multiwfn and dislin source code 
      run: |
        curl -L http://sobereva.com/multiwfn/misc/${{env.Multiwfn_version}}.zip -o Multiwfn_src.zip
        7z x Multiwfn_src.zip

        # dislin for windows mingw
        curl -L https://www.dislin.de/downloads/win64/dl_11_mg.zip -o dislin.zip --insecure
        unzip dislin.zip -d temp
        cp ./temp/dismg_d.a .
        ls

    - name: Build Multiwfn
      run: |
          cd ${{env.Multiwfn_version}}
          cp ..\CMakeLists.txt . 
          cp ..\dismg_d.a .
          md build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DMINGW=ON -DFLINT_DIR=C:\msys64\mingw64\lib\cmake\flint\flintConfig.cmake
          ninja install -j4

    - name: Test
      run: |
          ldd ./${{env.Multiwfn_version}}/build/Multiwfn.exe

    - name: Upload Multiwfn
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: Multiwfn_Win_MingW_x64
        path: |
          ./${{env.Multiwfn_version}}/build/Multiwfn.exe


