name: Build Multiwfn on Windows

on:
  push:
    branches:
      - master

env:
  Multiwfn_version:  Multiwfn_3.8_dev_src_Linux
  BUILD_TYPE: Debug
  WINDOWS_HPCKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/c95a3b26-fc45-496c-833b-df08b10297b9/w_HPCKit_p_2024.1.0.561_offline.exe
  WINDOWS_FORTRAN_COMPONENTS: intel.oneapi.win.ifort-compiler
  WINDOWS_MKL_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/78da61ee-8ded-4aab-8964-fea48243b05e/w_onemkl_p_2024.1.0.696_offline.exe
  WINDOWS_MKL_COMPONENTS: intel.oneapi.win.mkl.devel

jobs:
  Windows:
    runs-on: windows-2022

    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Cache Code
      #   id: cache-code
      #   uses: actions/cache@v4
      #   with:
      #     path: ${{github.workflow}}\${{env.Multiwfn_version}}\build
      #     key: ${{ runner.os }}-ifort-2025.0-code

      - name: "Setup cache for dependencies"
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Install flint dependencies via vcpkg
        run: |
          vcpkg install flint --binarysource="clear;x-gha,readwrite"

      # - name: Install Fortran compiler/MKL and Visual Studio 2022 integration
      #   run: |
      #     .github/scripts/install_ifort.bat ${{env.WINDOWS_MKL_URL}} ${{env.WINDOWS_MKL_COMPONENTS}}
      #     .github/scripts/install_ifort.bat ${{env.WINDOWS_HPCKIT_URL}} ${{env.WINDOWS_FORTRAN_COMPONENTS}}

      # - name: Activate compiler environment and Copy libiomp5md.dll to working directory
      #   run: |
      #     .github/scripts/activate_env.bat

      - name: Download Multiwfn source code
        run: |
          curl -L http://sobereva.com/multiwfn/misc/${{env.Multiwfn_version}}.zip -o Multiwfn_src.zip
          7z x Multiwfn_src.zip
        
      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
          toolset: 14.29

      - name: Compile Multiwfn
        shell: cmd
        run: |
          cd ${{env.Multiwfn_version}}
          copy ..\CMakeLists.txt . /Y
          copy ..\disifl_d.lib . /Y
          md build && cd build
          dir C:\vcpkg\packages\flint_x64-windows-release
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="C:/vcpkg/packages/flint_x64-windows-release" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -A x64
          cmake --build . --config ${{env.BUILD_TYPE}} --target Multiwfn 
          
          dir ${{env.BUILD_TYPE}}

      - name: Upload Multiwfn
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: Multiwfn_Win_x64
          path: |
            ${{env.Multiwfn_version}}\build\${{env.BUILD_TYPE}}\Multiwfn.exe
            .\libiomp5md.dll
