name: Build Multiwfn Linux64

on:
  push:
    branches:
      - master
      
env:
  Multiwfn_version:  Multiwfn_3.8_dev_src_Linux
  
jobs:
  Linux-64:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: Install Dislin libraries
      run: |
        sudo apt install libxm4 libmotif-dev libgl1-mesa-dev libgmp-dev libmpfr-dev

    - name: Test X11
      run: |
        grep AnyModifier /usr/include/X11/X.h
        grep AnyButton /usr/include/X11/X.h
        grep AnyKey /usr/include/X11/X.h
        grep GrabModeSync /usr/include/X11/X.h
        grep GrabModeAsync /usr/include/X11/X.h

    - name: Test fortran-xlib
      run: |
        git clone https://github.com/interkosmos/fortran-xlib.git
        cd fortran-xlib
        ifort -O2 -c src/xlib.f90
        ifort -O2 -c src/xpm.f90
        ar rcs libfortran-xlib.a xlib.o xpm.o
        ifort -o window examples/window/window.f90 libfortran-xlib.a -lX11
        ifort -o events examples/events/events.f90 libfortran-xlib.a -lX11
        ifort -o drawing examples/drawing/drawing.f90 libfortran-xlib.a -lX11

    - name: Upload exe
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: Prog
        path: |
          ./window
          ./events
          ./drawing

          

