name: Build Multiwfn Linux64

on:
  push:
    branches:
      - master
  
jobs:
  Linux-64:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: Install libraries
      run: |
        sudo apt install libxm4 libmotif-dev libgl1-mesa-dev libgmp-dev libmpfr-dev

    - name: Install Intel oneAPI compiler
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install intel-oneapi-compiler-fortran-2021.4.0 intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2021.4.0 intel-oneapi-mkl-2021.4.0 intel-oneapi-mkl-devel-2021.4.0
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV

    - name: Test fortran-xlib
      run: |
        git clone https://github.com/interkosmos/fortran-xlib.git
        cd fortran-xlib
        ifort -O2 -c src/xlib.f90
        ifort -O2 -c src/xpm.f90
        ar rcs libfortran-xlib.a xlib.o xpm.o
        ifort -o window examples/window/window.f90 libfortran-xlib.a -lX11
        ifort -o events examples/events/events.f90 libfortran-xlib.a -lX11
        ifort -o drawing examples/drawing/drawing.f90 libfortran-xlib.a -lX11

    - name: Upload exe
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: Prog
        path: |
          ./window
          ./events
          ./drawing

          

